= RC Elektronik
Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
:toc:
:toc-title: Inhalt
:toclevels: 4
:numbered:
:toc-placement!:

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

:ddir: https://wimalopaan.github.io/Electronics
:rcb: {ddir}/rc/boards

[NOTE]
--
Hier finden Sie Informationen zu den von mir entworfenen RC-Elektronik-Modulen, OpenTx-Addons, LUA-Scripting, und vieles mehr.
--

toc::[]

[TIP]
--
Die leeren Kapitel sind für mich Gedankenstützen, dass hier noch etwas zu tun ist ;-) 
--

== RC-Elektronik-Module

[[msd]]
=== RC-Multiswitch-D

Der `RC-Multiswitch-D` ist ein _digitales_ Schaltmodul mit 8-Kanälen

Anleitung: {rcb}/rcmultiswitch.html[RC MultiSwitch] {rcb}/rcmultiswitch_r.pdf[pdf]

Anleitung (Hott): {rcb}/rcmultiswitch_h.html[RC MultiSwitch] {rcb}/rcmultiswitch_h_r.pdf[pdf]

=== RC-MultiAdapter-DA

s.a. <<msd,RC-MultiSwitch-D>>

=== RC-ServoSwitch-D

s.a. <<msd,RC-MultiSwitch-D>>

=== RC-Quad-D

Anleitung: {rcb}/rcquad.html[RC Quad] {rcb}/rcquad_r.pdf[pdf]

=== RC-ThreeSixty-D

Schottelsteuerung

=== RC-Led-D

=== RC-Cellwatch

Anleitung: {rcb}/cellwatch.html[RC Cellwatch] {rcb}/cellwatch_r.pdf[pdf]

=== RC-SensorModul

=== RC-Hauptschalter

Anleitung: {rcb}/onoff_telemetrie.html[RC Hauptschalter] {rcb}/onoff_telemetrie_r.pdf[pdf]

=== DIY RC-Hauptschalter

Anleitung: {rcb}/onoff_simple.html[DIY RC Hauptschalter] {rcb}/onoff_simple_r.pdf[pdf]

=== RC-Akkuweiche

Die Anleitung enthält auch eine ausführliche Betrachtung über das Thema _Parallelschalten_ von Akkus.

Anleitung: {rcb}/power_or.html[Akkuweiche] {rcb}/power_or_r.pdf[pdf]

=== RC-BEC-Weiche

=== RC-Inkrementalgeber

Anleitung: {rcb}/rcincr.html[RC Inkrementalgeber] {rcb}/rcincr_r.pdf[pdf]

=== RC-Desk

=== Wassermelder

=== Elektronischer Schalter

== OpenTx

=== Schottelsteuerung

=== Voith-Schneider-Steuerung

=== OpenTx Weekly

https://www.youtube.com/channel/UCedl1hS-dfWh-V4WBz_jGog[YouTube]

== Anleitungen

=== Umbau 40MHz-JR-Sendermodul

== Audio

== Uhren

=== WordClock 1

=== WordClock 2

=== Binär-Uhr

=== Nixie-Uhr

=== Servo-Uhr

=== Fahradketten-Uhr

== License

Siehe auch link:LICENSE[Lizenz], sofern in der Anleitung, dem Code oder sonstigem Artefakt nicht anders angegeben.

== Kontakt

mailto:wilhelm.wm.meier@googlemail.com[email]
