= RC Elektronik

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

:ddir: https://wimalopaan.github.io/Electronics
:rcb: {ddir}/rc/boards

[NOTE]
--
Hier finden Sie Informationen zu den von mir entworfenen RC-Elektronik-Modulen, OpenTx-Addons, LUA-Scripting, und vieles mehr.
--

== RC-Elektronik-Module

[[msd]]
=== RC-Multiswitch-D

Der `RC-Multiswitch-D` ist ein _digitales_ Schaltmodul mit 8-Kanälen

Anleitung: {rcb}/rcmultiswitch.html[RC MultiSwitch] {rcb}/rcmultiswitch_r.pdf[pdf]

Anleitung (Hott): {rcb}/rcmultiswitch_h.html[RC MultiSwitch] {rcb}/rcmultiswitch_h_r.pdf[pdf]

=== RC-MultiAdapter-DA

s.a. <<msd,RC-MultiSwitch-D>>

=== RC-ServoSwitch-D

s.a. <<msd,RC-MultiSwitch-D>>

=== RC-Quad-D

Anleitung: {rcb}/rcquad.html[RC Quad] {rcb}/rcquad_r.pdf[pdf]

=== RC-Led-D

=== RC-Cellwatch

Anleitung: {rcb}/cellwatch.html[RC Cellwatch] {rcb}/cellwatch_r.pdf[pdf]

=== RC-SensorModul

=== RC-Hauptschalter

Anleitung: {rcb}/onoff_telemetrie.html[RC Hauptschalter] {rcb}/onoff_telemetrie_r.pdf[pdf]

=== DIY RC-Hauptschalter

Anleitung: {rcb}/onoff_simple.html[DIY RC Hauptschalter] {rcb}/onoff_simple_r.pdf[pdf]

=== RC-Akkuweiche

Anleitung: {rcb}/power_or.html[Akkuweiche] {rcb}/power_or_r.pdf[pdf]

=== RC-BEC-Weiche

=== RC-Inkrementalgeber

Anleitung: {rcb}/rcincr.html[RC Inkrementalgeber] {rcb}/rcincr_r.pdf[pdf]

=== RC-Desk

=== Wassermelder

== License

Siehe auch link:LICENSE[Lizenz]

== Kontakt

mailto:wilhelm.wm.meier@googlemail.com[email]
